import Login from "../../Components/Login";
import { getSession } from "next-auth/react";
import Header from "../../Components/Home/Header";
import InviteUsers from "../../Components/Domains/InviteUsers"
import Head from "next/head";
import { useEffect } from "react";

export default function Domains({ session, data }) {
  if (!session) return <Login />;
  return (
    <div className="">
      <Head>
        <title>Domains</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header props={{ first: "/", second: "/publications", third: "about" }} />
      <main className="h-fit">
        <InviteUsers data = {data} />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  const res = await fetch("http://localhost:8181/api/v1/profession/domain/size");
  const data = await res.json();
  return {
    props: { session, data },
  };
}
